Repository RychardHunt/hodl-invest, pull requests merged in 2018-04, with the labels that each got.

#106 minor login fix and refactoring
  client/hodl-invest/src/components/About.jsx
  client/hodl-invest/src/components/Login.jsx
Labels: enhancement

#116 fix minor signup/login issue
  client/hodl-invest/src/components/Login.jsx
Labels: enhancement

#124 redirect to dashboard after login
  client/hodl-invest/src/components/Login.jsx
Labels: bug, enhancement

#127 Converted Unix/Epoch Time
  .DS_Store
  client/hodl-invest/src/components/Chart.jsx
Labels: enhancement

#128 update alert messages
  client/hodl-invest/src/components/Login.jsx
Labels: enhancement

#173 Updated Transaction Panel
  client/hodl-invest/package-lock.json
  client/hodl-invest/package.json
  client/hodl-invest/src/components/BuySellPanel.jsx
  client/hodl-invest/src/components/Registration.css
  client/hodl-invest/src/components/Transaction.jsx
  client/hodl-invest/src/components/TransactionHistory.jsx
Labels: enhancement

#212 resolve transaction history minor bug
  client/hodl-invest/src/components/TransactionHistory.jsx
Labels: bug

#227 refactor and implement numerous feature requests
  client/hodl-invest/src/components/BuySellPanel.jsx
  client/hodl-invest/src/components/Chart.jsx
  client/hodl-invest/src/components/Charts.jsx
  client/hodl-invest/src/components/Dashboard.jsx
  client/hodl-invest/src/components/Registration.jsx
  client/hodl-invest/src/components/TransactionHistory.css
  client/hodl-invest/src/components/TransactionHistory.jsx
Labels: enhancement

#233 refactor registration
  client/hodl-invest/src/components/About.jsx
  client/hodl-invest/src/components/BuySellPanel.jsx
  client/hodl-invest/src/components/Login.jsx
  client/hodl-invest/src/components/Registration.jsx
Labels: Add On, enhancement
